<?php
$services=array(
	'system.requestHandler'=>array(
		'\\ZedBoot\\App\\Pages\\AjaxHandler',
		array('system.dependencyLoader','system.errorLogger'),
		true
	),
	'model'=>array(
		'\\ZedBoot\\App\\Pages\\ContactForm\\MailerModelTest',
		array('system.errorLogger','contact.email'),
		true
	),
	'ajax.controller'=>array(
		'\\ZedBoot\\App\\Pages\\ContactForm\\MailerController',
		array('system.errorLogger','model'),
		true
	),
	'ajax.view'=>array(
		'\\ZedBoot\\App\\Pages\\ContactForm\\MailerView',
		array('system.errorLogger','model'),
		true
	),
);
